### ISSUE TITLE
issue Communication

### ISSUE THREAD

**Issue by muwoo** [monkeyWangs/doubanMovie#1]
如果在项目中遇到了什么问题，在这里可以讨论交流

**Comment by Noobccc** [comment]
## 组件获取状态
在这个项目中，我看到你组件获取状态好像都是从getters中获取？看vuex文档,getter好像是用于派生一些状态，新手请教
`import {mapState} from 'vuex
...
computed:{...mapState(['searchList'])}`
和
`import {mapGetters} from 'vuex
...
computed:{...mapGetters(['searchList'])}`
哪种获取状态好？
