### ISSUE TITLE
nginx配置在项目中好像没有看到

### ISSUE THREAD

**Issue by AlenWang** [monkeyWangs/doubanMovie#7]
文章中说到的config/nginx.config在项目中好像并没有看到这个文件

**Comment by zhmars** [comment]
我觉得这里的意思应该是找到自己服务器上的 `nginx.conf`，再用说明里面的内容替换

**Comment by muwoo** [comment]
@AlenWang 如果你的服务器使用了ngix，可以使用下面readme的ngix配置文件替换.

**Comment by AlenWang** [comment]
通过proxyTable配置代理，是解决本地开发跨域问题；设置nginx文件是解决生产环境跨域问题。是这样的吧？
